dist: xenial
language: minimal
services:
- docker
before_install:
- make enforce
- make ci BINDIR=/usr/bin
- export BUILDKIT_HOST=tcp://0.0.0.0:1234
script:
- make
- make talos
- cd hack/dev
- make integration
- if [[ -n $(git status -s) ]];then echo 'working tree is dirty' && git status -s && exit 1; fi
branches:
  only:
  - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: V0IAN4j/jZkVb7B6ChmJajRj6GCLgL2O7V1XhU0d7dGvc30/ZS6nI5OS9xs58M0c8AeVUX+vfPztKnkTyri/Fpq2D9Clam1LBi3juRDA8kpxwIIt2WwNHjYHmNgqctiGNydNwgxXVoQhFgo/sAWeQSl0TxcbsCDPqB9yxnRmKUGfHvnr9tpZEOSMshtVCwrtMP77MmquIv3TQYNa81WZ5MLzBgt2TYqbisGXn2ApOGXmDCfjousTd5IwMadpKlez/42u9m8ZfRKV8zQgL6hWZYBCrGdGZMbFbxd2HHJ6TlFd+trz8KDKfsyUyeNBsDVB6vsZFVAHqPOMPPv/IZkCZMWGf8TZ8lc87r2t5Uufk+pQ2iqmAzAI58gItWtlZVlNHgYLHOomtpyCAw037SwJ9o68wsQ6MeH5QmJjdTzt9BGLfb6wZoPM7qz9/dw3vYWj2gHf19xRGIvsCafBGWWhlrrMl/2L3ng2+Xu8gZMqI+XoK1L8ycsEny1grpu2z6Y6pSdLWkDdtIJG8ITPKg6XwuMRs8Asvp21VWAZVJIV3iNR/AiPOzxiGKXeYzdIsTlHr0P8joRV5TcjLdkSVMSlNfTvgundUwJHQjw1D1q7zv88CaUVGmaffCHTVi37cHMAivM8Fde7OlsXxYaoAL5u2IHNNo3uJuKhpxiJ6SidWvM=
