version = 2

disabled_plugins = []

imports = ["/var/cri/conf.d/*.toml"]

[debug]
level = "info"
format = "json"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
    discard_unpacked_layers = true
