imports:
  - path: talos-ha.jinja

resources:
  - name: talos-ha
    type: talos-ha.jinja
    properties:
      zone: us-west2-c
      talosVersion: v0.13.2
      controlPlaneNodeCount: 3
      controlPlaneNodeType: n1-standard-1
      workerNodeCount: 1
      workerNodeType: n1-standard-1
outputs:
  - name: bucketName
    value: $(ref.talos-ha.bucketName)
